

using System;
using System.Collections;
using System.IO;
using System.Text.RegularExpressions;
using TheArtOfDev.HtmlRenderer.PdfSharp;
using System.Linq;
using System.Xml;
using System.Xml.XPath;
using System.Xml.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Xml.Serialization;
using Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1;

namespace PlayGround
{
    class Program
    {
        static void Main(string[] args)
        {
            string s = "900917640";
            int i = 6;
            string ss = s.Substring(0, i) + "/" + s.Substring(i);
            var cdrRequest = new CreateDataRequestRequest();
            cdrRequest.dataFOs = new DataFO[1];
            cdrRequest.dataFOs[0] = new DataFO();
            cdrRequest.dataFOs[0].dateOfBirth = DateTime.Now.Date;
            XmlSerializer xs = new XmlSerializer(typeof(CreateDataRequestRequest));

            using (var ms = new MemoryStream())
            {
                using (TextWriter txtWriter = new StreamWriter(ms))
                {
                    xs.Serialize(txtWriter, cdrRequest);
                    var q = System.Text.Encoding.UTF8.GetString(ms.ToArray());
                } 
            }

            Console.ReadLine();
        }

        
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", ConfigurationName = "ServiceReference1.MukWebServices")]
    public interface MukWebServices
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(fileType[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1 confirmRemoval(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1> confirmRemovalAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(fileType[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1 getData(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1> getDataAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(fileType[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1 createDataRequest(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1> createDataRequestAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(fileType[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1 getStatus(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1> getStatusAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class ConfirmRemovalRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private long dataQueryIdField;

        private long dataRequestIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long dataQueryId
        {
            get
            {
                return this.dataQueryIdField;
            }
            set
            {
                this.dataQueryIdField = value;
                this.RaisePropertyChanged("dataQueryId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long dataRequestId
        {
            get
            {
                return this.dataRequestIdField;
            }
            set
            {
                this.dataRequestIdField = value;
                this.RaisePropertyChanged("dataRequestId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class DataProperty : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string cadastralAreaCodeField;

        private string descriptionField;

        private propertySearchType propertySearchTypeField;

        private string propertySearchValueField;

        private int purposeCodeField;

        private string requesterIdField;

        private string subjectFirstParField;

        private string subjectSecondParField;

        private int subjectTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string cadastralAreaCode
        {
            get
            {
                return this.cadastralAreaCodeField;
            }
            set
            {
                this.cadastralAreaCodeField = value;
                this.RaisePropertyChanged("cadastralAreaCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public propertySearchType propertySearchType
        {
            get
            {
                return this.propertySearchTypeField;
            }
            set
            {
                this.propertySearchTypeField = value;
                this.RaisePropertyChanged("propertySearchType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string propertySearchValue
        {
            get
            {
                return this.propertySearchValueField;
            }
            set
            {
                this.propertySearchValueField = value;
                this.RaisePropertyChanged("propertySearchValue");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int purposeCode
        {
            get
            {
                return this.purposeCodeField;
            }
            set
            {
                this.purposeCodeField = value;
                this.RaisePropertyChanged("purposeCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string requesterId
        {
            get
            {
                return this.requesterIdField;
            }
            set
            {
                this.requesterIdField = value;
                this.RaisePropertyChanged("requesterId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string subjectFirstPar
        {
            get
            {
                return this.subjectFirstParField;
            }
            set
            {
                this.subjectFirstParField = value;
                this.RaisePropertyChanged("subjectFirstPar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string subjectSecondPar
        {
            get
            {
                return this.subjectSecondParField;
            }
            set
            {
                this.subjectSecondParField = value;
                this.RaisePropertyChanged("subjectSecondPar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public int subjectType
        {
            get
            {
                return this.subjectTypeField;
            }
            set
            {
                this.subjectTypeField = value;
                this.RaisePropertyChanged("subjectType");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum propertySearchType
    {

        /// <remarks/>
        LIST_VLASTNICTVA,

        /// <remarks/>
        PARCELA_REGISTRA_C,

        /// <remarks/>
        PARCELA_REGISTRA_E,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class DataPO : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string descriptionField;

        private string dicField;

        private string icoField;

        private string nameField;

        private string requesterIdField;

        private sourceRegister sourceRegisterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string dic
        {
            get
            {
                return this.dicField;
            }
            set
            {
                this.dicField = value;
                this.RaisePropertyChanged("dic");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
                this.RaisePropertyChanged("ico");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string requesterId
        {
            get
            {
                return this.requesterIdField;
            }
            set
            {
                this.requesterIdField = value;
                this.RaisePropertyChanged("requesterId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public sourceRegister sourceRegister
        {
            get
            {
                return this.sourceRegisterField;
            }
            set
            {
                this.sourceRegisterField = value;
                this.RaisePropertyChanged("sourceRegister");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum sourceRegister
    {

        /// <remarks/>
        OBCHODNY_REGISTER,

        /// <remarks/>
        ZIVNOSTENSKY_REGISTER,

        /// <remarks/>
        REGISTER_NADACII,

        /// <remarks/>
        REGISTER_NEINVESTICNYCH_FONDOV,

        /// <remarks/>
        REGISTER_NEZISKOVYCH_ORG,

        /// <remarks/>
        REGISTER_OBCIANSKYCH_ZDRUZ,

        /// <remarks/>
        REGISTER_ORG_S_MEDZ_PRVKOM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class DataFO : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string getBirthCountryField;

        private string getBirthCountyField;

        private string getBirthMunicipalityField;

        private string getBirthNationalityField;


        private bool dateOfBirthFieldSpecified;

        private string descriptionField;

        private string getFatherFirstNameField;

        private string getFatherLastNameField;

        private string givenNameField;

        private string idCardNumberField;

        private string getMotherFirstNameField;

        private string getMotherGivenNameField;

        private string getMotherLastNameField;

        private string nameField;

        private string personalIDField;

        private string requesterIdField;

        private string getResidenceField;

        private string sexCodeField;

        private string surnameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string getBirthCountry
        {
            get
            {
                return this.getBirthCountryField;
            }
            set
            {
                this.getBirthCountryField = value;
                this.RaisePropertyChanged("getBirthCountry");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string getBirthCounty
        {
            get
            {
                return this.getBirthCountyField;
            }
            set
            {
                this.getBirthCountyField = value;
                this.RaisePropertyChanged("getBirthCounty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string getBirthMunicipality
        {
            get
            {
                return this.getBirthMunicipalityField;
            }
            set
            {
                this.getBirthMunicipalityField = value;
                this.RaisePropertyChanged("getBirthMunicipality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string getBirthNationality
        {
            get
            {
                return this.getBirthNationalityField;
            }
            set
            {
                this.getBirthNationalityField = value;
                this.RaisePropertyChanged("getBirthNationality");
            }
        }

        [System.Xml.Serialization.XmlIgnore]
        private string _xmlDatum;

        [System.Xml.Serialization.XmlElement(ElementName = "dateOfBirth", Order = 4, Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlDatum
        {
            get
            {
                return _xmlDatum;
            }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && System.DateTime.TryParse(value, out var x))
                {
                    this.dateOfBirthField = x;
                    _xmlDatum = value;
                }
                else
                {
                    this.dateOfBirthField = null;
                    _xmlDatum = null;
                }
            }
        }

        [System.Xml.Serialization.XmlIgnore]
        private System.DateTime? dateOfBirthField;

        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime? dateOfBirth
        {
            get
            {
                return dateOfBirthField;
            }
            set
            {
                dateOfBirthField = value;
                _xmlDatum = value?.ToString("yyyy-MM-dd");
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        //public System.DateTime dateOfBirth {
        //    get {
        //        return this.dateOfBirthField;
        //    }
        //    set {
        //        this.dateOfBirthField = value;
        //        this.RaisePropertyChanged("dateOfBirth");
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOfBirthSpecified
        {
            get
            {
                return this.dateOfBirthFieldSpecified;
            }
            set
            {
                this.dateOfBirthFieldSpecified = value;
                this.RaisePropertyChanged("dateOfBirthSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string getFatherFirstName
        {
            get
            {
                return this.getFatherFirstNameField;
            }
            set
            {
                this.getFatherFirstNameField = value;
                this.RaisePropertyChanged("getFatherFirstName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string getFatherLastName
        {
            get
            {
                return this.getFatherLastNameField;
            }
            set
            {
                this.getFatherLastNameField = value;
                this.RaisePropertyChanged("getFatherLastName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string givenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string idCardNumber
        {
            get
            {
                return this.idCardNumberField;
            }
            set
            {
                this.idCardNumberField = value;
                this.RaisePropertyChanged("idCardNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string getMotherFirstName
        {
            get
            {
                return this.getMotherFirstNameField;
            }
            set
            {
                this.getMotherFirstNameField = value;
                this.RaisePropertyChanged("getMotherFirstName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string getMotherGivenName
        {
            get
            {
                return this.getMotherGivenNameField;
            }
            set
            {
                this.getMotherGivenNameField = value;
                this.RaisePropertyChanged("getMotherGivenName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string getMotherLastName
        {
            get
            {
                return this.getMotherLastNameField;
            }
            set
            {
                this.getMotherLastNameField = value;
                this.RaisePropertyChanged("getMotherLastName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string personalID
        {
            get
            {
                return this.personalIDField;
            }
            set
            {
                this.personalIDField = value;
                this.RaisePropertyChanged("personalID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string requesterId
        {
            get
            {
                return this.requesterIdField;
            }
            set
            {
                this.requesterIdField = value;
                this.RaisePropertyChanged("requesterId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string getResidence
        {
            get
            {
                return this.getResidenceField;
            }
            set
            {
                this.getResidenceField = value;
                this.RaisePropertyChanged("getResidence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string sexCode
        {
            get
            {
                return this.sexCodeField;
            }
            set
            {
                this.sexCodeField = value;
                this.RaisePropertyChanged("sexCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class DataAddress : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string countyField;

        private string descriptionField;

        private string districtField;

        private string municipalityField;

        private string regionField;

        private string requesterIdField;

        private string streetField;

        private string streetNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string county
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
                this.RaisePropertyChanged("county");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string municipality
        {
            get
            {
                return this.municipalityField;
            }
            set
            {
                this.municipalityField = value;
                this.RaisePropertyChanged("municipality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string requesterId
        {
            get
            {
                return this.requesterIdField;
            }
            set
            {
                this.requesterIdField = value;
                this.RaisePropertyChanged("requesterId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string streetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
                this.RaisePropertyChanged("streetNumber");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class CreateDataRequestRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string applicantTypeField;

        private DataAddress[] dataAddressesField;

        private DataFO[] dataFOsField;

        private DataPO[] dataPOsField;

        private DataProperty[] dataPropertiesField;

        private string ownerField;

        private string recordNumberField;

        private System.DateTime requestCreatedField;

        private bool requestCreatedFieldSpecified;

        private string requestReasonField;

        private string requestedByISField;

        private string requestedByPersonEmailField;

        private string requestedByPersonNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string applicantType
        {
            get
            {
                return this.applicantTypeField;
            }
            set
            {
                this.applicantTypeField = value;
                this.RaisePropertyChanged("applicantType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAddress", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DataAddress[] dataAddresses
        {
            get
            {
                return this.dataAddressesField;
            }
            set
            {
                this.dataAddressesField = value;
                this.RaisePropertyChanged("dataAddresses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataFO", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DataFO[] dataFOs
        {
            get
            {
                return this.dataFOsField;
            }
            set
            {
                this.dataFOsField = value;
                this.RaisePropertyChanged("dataFOs");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataPO", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DataPO[] dataPOs
        {
            get
            {
                return this.dataPOsField;
            }
            set
            {
                this.dataPOsField = value;
                this.RaisePropertyChanged("dataPOs");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataProperty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DataProperty[] dataProperties
        {
            get
            {
                return this.dataPropertiesField;
            }
            set
            {
                this.dataPropertiesField = value;
                this.RaisePropertyChanged("dataProperties");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string recordNumber
        {
            get
            {
                return this.recordNumberField;
            }
            set
            {
                this.recordNumberField = value;
                this.RaisePropertyChanged("recordNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime requestCreated
        {
            get
            {
                return this.requestCreatedField;
            }
            set
            {
                this.requestCreatedField = value;
                this.RaisePropertyChanged("requestCreated");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestCreatedSpecified
        {
            get
            {
                return this.requestCreatedFieldSpecified;
            }
            set
            {
                this.requestCreatedFieldSpecified = value;
                this.RaisePropertyChanged("requestCreatedSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string requestReason
        {
            get
            {
                return this.requestReasonField;
            }
            set
            {
                this.requestReasonField = value;
                this.RaisePropertyChanged("requestReason");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string requestedByIS
        {
            get
            {
                return this.requestedByISField;
            }
            set
            {
                this.requestedByISField = value;
                this.RaisePropertyChanged("requestedByIS");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string requestedByPersonEmail
        {
            get
            {
                return this.requestedByPersonEmailField;
            }
            set
            {
                this.requestedByPersonEmailField = value;
                this.RaisePropertyChanged("requestedByPersonEmail");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string requestedByPersonName
        {
            get
            {
                return this.requestedByPersonNameField;
            }
            set
            {
                this.requestedByPersonNameField = value;
                this.RaisePropertyChanged("requestedByPersonName");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class GetDataRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private long dataQueryIdField;

        private long dataRequestIdField;

        private fileType fileTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long dataQueryId
        {
            get
            {
                return this.dataQueryIdField;
            }
            set
            {
                this.dataQueryIdField = value;
                this.RaisePropertyChanged("dataQueryId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long dataRequestId
        {
            get
            {
                return this.dataRequestIdField;
            }
            set
            {
                this.dataRequestIdField = value;
                this.RaisePropertyChanged("dataRequestId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public fileType fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
                this.RaisePropertyChanged("fileType");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum fileType
    {

        /// <remarks/>
        XML,

        /// <remarks/>
        PDF,

        /// <remarks/>
        PDF_EXTENDED,

        /// <remarks/>
        SIGNED_DATA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class DataQuery : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string descriptionField;

        private string errorMessageField;

        private fileType[] fileTypesField;

        private long idField;

        private oeType oeTypeField;

        private string requesterIdField;

        private dataQueryStatus statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public fileType[] fileTypes
        {
            get
            {
                return this.fileTypesField;
            }
            set
            {
                this.fileTypesField = value;
                this.RaisePropertyChanged("fileTypes");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public oeType oeType
        {
            get
            {
                return this.oeTypeField;
            }
            set
            {
                this.oeTypeField = value;
                this.RaisePropertyChanged("oeType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string requesterId
        {
            get
            {
                return this.requesterIdField;
            }
            set
            {
                this.requesterIdField = value;
                this.RaisePropertyChanged("requesterId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public dataQueryStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum oeType
    {

        /// <remarks/>
        FS_NEDOPLATKY,

        /// <remarks/>
        SP_NEDOPLATKY_Oversi,

        /// <remarks/>
        ZP_Odvodova_Povinnost,

        /// <remarks/>
        DEMINIMIS,

        /// <remarks/>
        RA,

        /// <remarks/>
        UGKK,

        /// <remarks/>
        RFO,

        /// <remarks/>
        RT,

        /// <remarks/>
        REG_UPADCOV,

        /// <remarks/>
        RPO,

        /// <remarks/>
        OBCHODNY_REGISTER,

        /// <remarks/>
        ZIVNOSTENSKY_REGISTER,

        /// <remarks/>
        REGISTER_NADACII,

        /// <remarks/>
        REGISTER_NEINVESTICNYCH_FONDOV,

        /// <remarks/>
        REGISTER_NEZISKOVYCH_ORG,

        /// <remarks/>
        REGISTER_OBCIANSKYCH_ZDRUZ,

        /// <remarks/>
        REGISTER_ORG_S_MEDZ_PRVKOM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum dataQueryStatus
    {

        /// <remarks/>
        NEW,

        /// <remarks/>
        SENT,

        /// <remarks/>
        DATA_READY,

        /// <remarks/>
        SUBJECT_NOT_FOUND,

        /// <remarks/>
        SOME_DATA_NOT_FOUND,

        /// <remarks/>
        FINISHED_SUCCESSFUL,

        /// <remarks/>
        FINISHED_WITH_WARNING,

        /// <remarks/>
        FINISHED_WITH_ERROR,

        /// <remarks/>
        CANCELLED,

        /// <remarks/>
        DELETE_DATA,

        /// <remarks/>
        DELETED_SUCCESSFUL,

        /// <remarks/>
        ERROR_DELETE_DATA,

        /// <remarks/>
        ERROR_SENT,

        /// <remarks/>
        ERROR_DATA,

        /// <remarks/>
        ERROR_FILE,

        /// <remarks/>
        EXPIRED,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStatusResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDataRequestResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmRemovalResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public abstract partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string errorMessageField;

        private resultCode resultCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public resultCode resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum resultCode
    {

        /// <remarks/>
        OK,

        /// <remarks/>
        INPUT_ERROR,

        /// <remarks/>
        INPUT_ERROR_UNKNOWN_ID,

        /// <remarks/>
        INPUT_ERROR_UNKNOWN_FILETYPE,

        /// <remarks/>
        INPUT_ERROR_ID_MISMATCH,

        /// <remarks/>
        INPUT_ERROR_TYPE_MISMATCH,

        /// <remarks/>
        OTHER_ERROR,

        /// <remarks/>
        SYSTEM_ERROR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class GetStatusResponse : ServiceResponse
    {

        private string applicantTypeField;

        private System.DateTime createdField;

        private string createdByField;

        private DataQuery[] dataQueriesField;

        private long dataRequestIdField;

        private dataRequestStatus dataRequestStatusField;

        private string ownerField;

        private string recordNumberField;

        private string requestReasonField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string applicantType
        {
            get
            {
                return this.applicantTypeField;
            }
            set
            {
                this.applicantTypeField = value;
                this.RaisePropertyChanged("applicantType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string createdBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataQuery", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DataQuery[] dataQueries
        {
            get
            {
                return this.dataQueriesField;
            }
            set
            {
                this.dataQueriesField = value;
                this.RaisePropertyChanged("dataQueries");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public long dataRequestId
        {
            get
            {
                return this.dataRequestIdField;
            }
            set
            {
                this.dataRequestIdField = value;
                this.RaisePropertyChanged("dataRequestId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public dataRequestStatus dataRequestStatus
        {
            get
            {
                return this.dataRequestStatusField;
            }
            set
            {
                this.dataRequestStatusField = value;
                this.RaisePropertyChanged("dataRequestStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string recordNumber
        {
            get
            {
                return this.recordNumberField;
            }
            set
            {
                this.recordNumberField = value;
                this.RaisePropertyChanged("recordNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string requestReason
        {
            get
            {
                return this.requestReasonField;
            }
            set
            {
                this.requestReasonField = value;
                this.RaisePropertyChanged("requestReason");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public enum dataRequestStatus
    {

        /// <remarks/>
        NEW,

        /// <remarks/>
        IN_PROGRESS,

        /// <remarks/>
        FINISHED_SUCCESSFUL,

        /// <remarks/>
        FINISHED_ERROR,

        /// <remarks/>
        CANCELLED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class CreateDataRequestResponse : ServiceResponse
    {

        private long dataRequestIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long dataRequestId
        {
            get
            {
                return this.dataRequestIdField;
            }
            set
            {
                this.dataRequestIdField = value;
                this.RaisePropertyChanged("dataRequestId");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class GetDataResponse : ServiceResponse
    {

        private long dataQueryIdField;

        private long dataRequestIdField;

        private byte[] fileField;

        private string mimeTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long dataQueryId
        {
            get
            {
                return this.dataQueryIdField;
            }
            set
            {
                this.dataQueryIdField = value;
                this.RaisePropertyChanged("dataQueryId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long dataRequestId
        {
            get
            {
                return this.dataRequestIdField;
            }
            set
            {
                this.dataRequestIdField = value;
                this.RaisePropertyChanged("dataRequestId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 2)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
                this.RaisePropertyChanged("file");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/")]
    public partial class ConfirmRemovalResponse : ServiceResponse
    {

        private System.DateTime createdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "confirmRemoval", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class confirmRemoval
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalRequest confirmRemovalRequest;

        public confirmRemoval()
        {
        }

        public confirmRemoval(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalRequest confirmRemovalRequest)
        {
            this.confirmRemovalRequest = confirmRemovalRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "confirmRemovalResponse", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class confirmRemovalResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalResponse @return;

        public confirmRemovalResponse1()
        {
        }

        public confirmRemovalResponse1(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getData", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class getData
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataRequest getDataRequest;

        public getData()
        {
        }

        public getData(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataRequest getDataRequest)
        {
            this.getDataRequest = getDataRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getDataResponse", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class getDataResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataResponse @return;

        public getDataResponse1()
        {
        }

        public getDataResponse1(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "createDataRequest", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class createDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestRequest createDataRequestRequest;

        public createDataRequest()
        {
        }

        public createDataRequest(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestRequest createDataRequestRequest)
        {
            this.createDataRequestRequest = createDataRequestRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "createDataRequestResponse", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class createDataRequestResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestResponse @return;

        public createDataRequestResponse1()
        {
        }

        public createDataRequestResponse1(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getStatus", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class getStatus
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long dataRequestId;

        public getStatus()
        {
        }

        public getStatus(long dataRequestId)
        {
            this.dataRequestId = dataRequestId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getStatusResponse", WrapperNamespace = "http://web.qsign.ardaco.com/MukWebServices/", IsWrapped = true)]
    public partial class getStatusResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://web.qsign.ardaco.com/MukWebServices/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetStatusResponse @return;

        public getStatusResponse1()
        {
        }

        public getStatusResponse1(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetStatusResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MukWebServicesChannel : Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MukWebServicesClient : System.ServiceModel.ClientBase<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices>, Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices
    {

        public MukWebServicesClient()
        {
        }

        public MukWebServicesClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public MukWebServicesClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MukWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MukWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1 Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.confirmRemoval(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval request)
        {
            return base.Channel.confirmRemoval(request);
        }

        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalResponse confirmRemoval(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalRequest confirmRemovalRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval();
            inValue.confirmRemovalRequest = confirmRemovalRequest;
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1 retVal = ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).confirmRemoval(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1> Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.confirmRemovalAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval request)
        {
            return base.Channel.confirmRemovalAsync(request);
        }

        public System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemovalResponse1> confirmRemovalAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.ConfirmRemovalRequest confirmRemovalRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.confirmRemoval();
            inValue.confirmRemovalRequest = confirmRemovalRequest;
            return ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).confirmRemovalAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1 Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.getData(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData request)
        {
            return base.Channel.getData(request);
        }

        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataResponse getData(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataRequest getDataRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData();
            inValue.getDataRequest = getDataRequest;
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1 retVal = ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).getData(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1> Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.getDataAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData request)
        {
            return base.Channel.getDataAsync(request);
        }

        public System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getDataResponse1> getDataAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetDataRequest getDataRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getData();
            inValue.getDataRequest = getDataRequest;
            return ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).getDataAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1 Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.createDataRequest(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest request)
        {
            return base.Channel.createDataRequest(request);
        }

        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestResponse createDataRequest(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestRequest createDataRequestRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest();
            inValue.createDataRequestRequest = createDataRequestRequest;
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1 retVal = ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).createDataRequest(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1> Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.createDataRequestAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest request)
        {
            return base.Channel.createDataRequestAsync(request);
        }

        public System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequestResponse1> createDataRequestAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.CreateDataRequestRequest createDataRequestRequest)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.createDataRequest();
            inValue.createDataRequestRequest = createDataRequestRequest;
            return ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).createDataRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1 Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.getStatus(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus request)
        {
            return base.Channel.getStatus(request);
        }

        public Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.GetStatusResponse getStatus(long dataRequestId)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus();
            inValue.dataRequestId = dataRequestId;
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1 retVal = ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).getStatus(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1> Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices.getStatusAsync(Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus request)
        {
            return base.Channel.getStatusAsync(request);
        }

        public System.Threading.Tasks.Task<Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatusResponse1> getStatusAsync(long dataRequestId)
        {
            Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus inValue = new Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.getStatus();
            inValue.dataRequestId = dataRequestId;
            return ((Nuntio.NET.WindowsServicePlugin.MKU.LMSender.ServiceReference1.MukWebServices)(this)).getStatusAsync(inValue);
        }
    }
}

